node_agg_fn: 'sum'
num_enc_steps: 1  # before 4 Number of message passing steps
num_class_steps: 1  # before 3Number of message passing steps during feature vectors are classified (after Message Passing)
reattach_initial_nodes: False  # elg. Original: False Determines whether initially encoded node feats are used during node updates
reattach_initial_edges: False  #  elg. Original: TrueDetermines whether initially encoded edge feats are used during node updates

encoder_feats_dict:
  edges:
    edge_in_dim: 2 # elg: 2 if only appearance or only dist
    edge_fc_dims: [4] #elg before [6]
    edge_out_dim: 4 # elg: original = 16 ours 1 if not encoding

  nodes:
    node_in_dim: 2048
    node_fc_dims: [1024,512, 128]
    node_out_dim: 32
    dropout_p: 0.1
    use_batchnorm: True

# MPN EDGE UPDATE
edge_model_feats_dict:
  fc_dims: [4] #  before 66,6elg: orig [80,16]In size is 4 * encoded nodes + 2 * encoded edges
  dropout_p: 0.1
  use_batchnorm: True

# MPN NODE UPDATE
node_model_feats_dict:
  fc_dims: [32]  # elg: orig [56,32] In size is 2 * encoded nodes + 1 * encoded edges
  dropout_p: 0.1
  use_batchnorm: True

classifier_feats_dict:
  edge_in_dim: 4 #orig 16
  edge_fc_dims: [] # orig
  edge_out_dim: 2
  dropout_p: 0
  use_batchnorm: False
  is_classifier: True