06_hyperparameter_tuning:

  experiment_params:
    num_trials: 9
    experiment_name: "table_5_enc_bs_grid"
    sampler: "grid" #"grid"
  dataset_params:
    sequence_path: "datasets/AIC20/"
    test_sequence: 'S02'
    gt_filename: "gt_roi_filtered.txt"
    sct_filename: "mtsc_tnt_ssd512_roi_filtered.txt"
    eval_metric: macro_f1_score
  hyperparam_toggles:
    modify_gnn_config: gallery_gnn
    enable_negative_sampling: False
    enable_dynamic_weights: False
  search_space:

    # Dataset related
    ratio_neg_links_graph: [1] # 1 means original ratio
    num_ids_per_graph: [32, 64, 100]

    # Training related
    lr: [0.01]
    epochs: [100] 
    warmup_duration: [10] # 0 is no warmup
    optimizer_momentum: [0.9] # 0 is no momentum
    lr_scheduler_step_size: [50] # 0 is scheduler off


    # GNN architecture
    #message_passing_steps: [1]
    #node_enc_fc_layers: [1] # Feat num decrease /2 every layer
    #edge_enc_fc_layers: [3] # Feat num increase x2 every layer
    #node_update_fc_layers: [3] # Channels icnrease x2 every layer
    #edge_update_fc_layers: [1] # Channels increase x2 every layer
    #edge_update_units: [64]

    # Gallery combinator
    input_format: ['gallery']
    gallery_combination: ['gru', 'mlp', 'linear']
    combinator_num_layers: [2]

    # Postprocessing toggles
    pruning: [True]
    spliting: [True]

